-- MySQL Script generated by MySQL Workbench
-- lun 18 may 2020 10:59:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `usuario` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `administrador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mapa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mapa` (
  `idMapa` INT NOT NULL,
  PRIMARY KEY (`idMapa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subdivision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Subdivision` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Subdivision` (
  `idSubdivision` INT NOT NULL,
  `idMapa` INT NOT NULL,
  PRIMARY KEY (`idSubdivision`, `idMapa`),
  INDEX `idMapa_idx` (`idMapa` ASC) VISIBLE,
  CONSTRAINT `idMapa`
    FOREIGN KEY (`idMapa`)
    REFERENCES `mydb`.`Mapa` (`idMapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Registro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Registro` (
  `fecha` DATE NOT NULL,
  `idSubdivision` INT NOT NULL,
  `recuperados` INT NOT NULL,
  `fallecidos` INT NOT NULL,
  `casa` INT NOT NULL,
  `hospital` INT NOT NULL,
  `uci` INT NOT NULL,
  `femeninos` INT NOT NULL,
  `masculinos` INT NOT NULL,
  `visitas` INT NOT NULL,
  PRIMARY KEY (`fecha`, `idSubdivision`),
  INDEX `idSubdivision_idx` (`idSubdivision` ASC) VISIBLE,
  CONSTRAINT `idSubdivision`
    FOREIGN KEY (`idSubdivision`)
    REFERENCES `mydb`.`Subdivision` (`idSubdivision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fallecidosEdad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fallecidosEdad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fallecidosEdad` (
  `fecha` DATE NOT NULL,
  `idSubdivision` INT NOT NULL,
  `cero` INT NOT NULL,
  `diez` INT NOT NULL,
  `veinte` INT NOT NULL,
  `treinta` INT NOT NULL,
  `cuarenta` INT NOT NULL,
  `cincuenta` INT NOT NULL,
  `sesenta` INT NOT NULL,
  `setenta` INT NOT NULL,
  `ochenta` INT NOT NULL,
  `noventa` INT NOT NULL,
  PRIMARY KEY (`fecha`, `idSubdivision`),
  INDEX `idSubdivision_idx` (`idSubdivision` ASC) VISIBLE,
  CONSTRAINT `fecha`
    FOREIGN KEY (`fecha`)
    REFERENCES `mydb`.`Registro` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSubdivision`
    FOREIGN KEY (`idSubdivision`)
    REFERENCES `mydb`.`Registro` (`idSubdivision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recuperadosEdad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recuperadosEdad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recuperadosEdad` (
  `fecha` DATE NOT NULL,
  `idSubdivision` INT NOT NULL,
  `cero` INT NOT NULL,
  `diez` INT NOT NULL,
  `veinte` INT NOT NULL,
  `treinta` INT NOT NULL,
  `cuarenta` INT NOT NULL,
  `cincuenta` INT NOT NULL,
  `sesenta` INT NOT NULL,
  `setenta` INT NOT NULL,
  `ochenta` INT NOT NULL,
  `noventa` INT NOT NULL,
  PRIMARY KEY (`fecha`, `idSubdivision`),
  INDEX `idSubdivision_idx` (`idSubdivision` ASC) VISIBLE,
  CONSTRAINT `fecha`
    FOREIGN KEY (`fecha`)
    REFERENCES `mydb`.`Registro` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSubdivision`
    FOREIGN KEY (`idSubdivision`)
    REFERENCES `mydb`.`Subdivision` (`idSubdivision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`confirmadosEdad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`confirmadosEdad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`confirmadosEdad` (
  `fecha` DATE NOT NULL,
  `idSubdivision` INT NOT NULL,
  `cero` INT NOT NULL,
  `diez` INT NOT NULL,
  `veinte` INT NOT NULL,
  `treinta` INT NOT NULL,
  `cuarenta` INT NOT NULL,
  `cincuenta` INT NOT NULL,
  `sesenta` INT NOT NULL,
  `setenta` INT NOT NULL,
  `ochenta` INT NOT NULL,
  `noventa` INT NOT NULL,
  PRIMARY KEY (`fecha`, `idSubdivision`),
  INDEX `idSubdivision_idx` (`idSubdivision` ASC) VISIBLE,
  CONSTRAINT `fecha`
    FOREIGN KEY (`fecha`)
    REFERENCES `mydb`.`Registro` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSubdivision`
    FOREIGN KEY (`idSubdivision`)
    REFERENCES `mydb`.`Registro` (`idSubdivision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
